package link.ebbinghaus.planning.core.model.server.po;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PK_USER_ID
	 * @mbggenerated
	 */
	private Integer pkUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PASSWORD
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.NICKNAME
	 * @mbggenerated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PHONENUMBER
	 * @mbggenerated
	 */
	private String phonenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.EMAIL
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.GROUP
	 * @mbggenerated
	 */
	private Byte group;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.LEVEL
	 * @mbggenerated
	 */
	private Short level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.COINS
	 * @mbggenerated
	 */
	private Integer coins;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.TOTAL_KNOWLEDGE_QUANTITY
	 * @mbggenerated
	 */
	private Integer totalKnowledgeQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.GENDER
	 * @mbggenerated
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.AVATAR
	 * @mbggenerated
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.SIGNATURE
	 * @mbggenerated
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.DB_SYNC_TIME
	 * @mbggenerated
	 */
	private Date dbSyncTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.DB_URL
	 * @mbggenerated
	 */
	private String dbUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ACHIEVEMENT_SYNC_TIME
	 * @mbggenerated
	 */
	private Date achievementSyncTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.TOKEN
	 * @mbggenerated
	 */
	private String token;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PK_USER_ID
	 * @return  the value of user.PK_USER_ID
	 * @mbggenerated
	 */
	public Integer getPkUserId() {
		return pkUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PK_USER_ID
	 * @param pkUserId  the value for user.PK_USER_ID
	 * @mbggenerated
	 */
	public void setPkUserId(Integer pkUserId) {
		this.pkUserId = pkUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PASSWORD
	 * @return  the value of user.PASSWORD
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PASSWORD
	 * @param password  the value for user.PASSWORD
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.NICKNAME
	 * @return  the value of user.NICKNAME
	 * @mbggenerated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.NICKNAME
	 * @param nickname  the value for user.NICKNAME
	 * @mbggenerated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PHONENUMBER
	 * @return  the value of user.PHONENUMBER
	 * @mbggenerated
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PHONENUMBER
	 * @param phonenumber  the value for user.PHONENUMBER
	 * @mbggenerated
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.EMAIL
	 * @return  the value of user.EMAIL
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.EMAIL
	 * @param email  the value for user.EMAIL
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.GROUP
	 * @return  the value of user.GROUP
	 * @mbggenerated
	 */
	public Byte getGroup() {
		return group;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.GROUP
	 * @param group  the value for user.GROUP
	 * @mbggenerated
	 */
	public void setGroup(Byte group) {
		this.group = group;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.LEVEL
	 * @return  the value of user.LEVEL
	 * @mbggenerated
	 */
	public Short getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.LEVEL
	 * @param level  the value for user.LEVEL
	 * @mbggenerated
	 */
	public void setLevel(Short level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.COINS
	 * @return  the value of user.COINS
	 * @mbggenerated
	 */
	public Integer getCoins() {
		return coins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.COINS
	 * @param coins  the value for user.COINS
	 * @mbggenerated
	 */
	public void setCoins(Integer coins) {
		this.coins = coins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.TOTAL_KNOWLEDGE_QUANTITY
	 * @return  the value of user.TOTAL_KNOWLEDGE_QUANTITY
	 * @mbggenerated
	 */
	public Integer getTotalKnowledgeQuantity() {
		return totalKnowledgeQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.TOTAL_KNOWLEDGE_QUANTITY
	 * @param totalKnowledgeQuantity  the value for user.TOTAL_KNOWLEDGE_QUANTITY
	 * @mbggenerated
	 */
	public void setTotalKnowledgeQuantity(Integer totalKnowledgeQuantity) {
		this.totalKnowledgeQuantity = totalKnowledgeQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.GENDER
	 * @return  the value of user.GENDER
	 * @mbggenerated
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.GENDER
	 * @param gender  the value for user.GENDER
	 * @mbggenerated
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.AVATAR
	 * @return  the value of user.AVATAR
	 * @mbggenerated
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.AVATAR
	 * @param avatar  the value for user.AVATAR
	 * @mbggenerated
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.SIGNATURE
	 * @return  the value of user.SIGNATURE
	 * @mbggenerated
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.SIGNATURE
	 * @param signature  the value for user.SIGNATURE
	 * @mbggenerated
	 */
	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.CREATE_TIME
	 * @return  the value of user.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.CREATE_TIME
	 * @param createTime  the value for user.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.DB_SYNC_TIME
	 * @return  the value of user.DB_SYNC_TIME
	 * @mbggenerated
	 */
	public Date getDbSyncTime() {
		return dbSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.DB_SYNC_TIME
	 * @param dbSyncTime  the value for user.DB_SYNC_TIME
	 * @mbggenerated
	 */
	public void setDbSyncTime(Date dbSyncTime) {
		this.dbSyncTime = dbSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.DB_URL
	 * @return  the value of user.DB_URL
	 * @mbggenerated
	 */
	public String getDbUrl() {
		return dbUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.DB_URL
	 * @param dbUrl  the value for user.DB_URL
	 * @mbggenerated
	 */
	public void setDbUrl(String dbUrl) {
		this.dbUrl = dbUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ACHIEVEMENT_SYNC_TIME
	 * @return  the value of user.ACHIEVEMENT_SYNC_TIME
	 * @mbggenerated
	 */
	public Date getAchievementSyncTime() {
		return achievementSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ACHIEVEMENT_SYNC_TIME
	 * @param achievementSyncTime  the value for user.ACHIEVEMENT_SYNC_TIME
	 * @mbggenerated
	 */
	public void setAchievementSyncTime(Date achievementSyncTime) {
		this.achievementSyncTime = achievementSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.TOKEN
	 * @return  the value of user.TOKEN
	 * @mbggenerated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.TOKEN
	 * @param token  the value for user.TOKEN
	 * @mbggenerated
	 */
	public void setToken(String token) {
		this.token = token;
	}
}